name: Build and Deploy NodeJS App to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build Docker Image and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t 559050236729.dkr.ecr.us-east-1.amazonaws.com/dev/nodeimages:latest .

      - name: Push Docker Image to ECR
        run: |
          docker push 559050236729.dkr.ecr.us-east-1.amazonaws.com/dev/nodeimages:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task.json
          service: devopsmolvi-ecs-srv
          cluster: devopsmolvi-ecs
          wait-for-service-stability: true
